module.exports = {
  START: "START",
  MAIN_MENU: "MAIN_MENU",
  PLAN_TRIP: "PLAN_TRIP",
  SELECT_DESTINATION: "SELECT_DESTINATION",
  SELECT_DAYS: "SELECT_DAYS",
  SELECT_TRAVELLERS: "SELECT_TRAVELLERS",
  SELECT_TRAVEL_MONTH: "SELECT_TRAVEL_MONTH",
  SELECT_BUDGET: "SELECT_BUDGET",
  SHOW_ITINERARY: "SHOW_ITINERARY",
  MODIFICATION: "MODIFICATION",
  MODIFY_VALUE: "MODIFY_VALUE",

  BUDGET_CALCULATOR: "BUDGET_CALCULATOR",
  BUDGET_SELECT_DESTINATION: "BUDGET_SELECT_DESTINATION",
  BUDGET_SELECT_TRAVELLERS: "BUDGET_SELECT_TRAVELLERS",
  BUDGET_SELECT_DAYS: "BUDGET_SELECT_DAYS",

  EXPLORE_DESTINATION: "EXPLORE_DESTINATION",
  VISA_INFO: "VISA_INFO",
  WEATHER: "WEATHER",
  BEST_TIME: "BEST_TIME",
  PACKING_LIST: "PACKING_LIST",
  TRAVEL_TIPS: "TRAVEL_TIPS",
  QUIZ: "QUIZ",
  QUOTE: "QUOTE",
  CONTACT_AGENT: "CONTACT_AGENT"
};
